spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: 
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
jwt:
  secret: wolf0295uoknff90u40eihq0123@o0845#$irqapwsour
  access-token-exp-min:15
  refresh-token-exp-days:15
  issuer:"wolf-dir"
spring.application.name=Wolf

app:
    oauth2:
        redirect-uri: http://localhost:8080/oauth2/callback/{registrationId}

spring.security.oauth2.client.registration:
    google:
        client-id: "YOUR_GOOGLE_CLIENT_ID"
        client-secret: "YOUR_GOOGLE_CLIENT_SECRET"
        scope:
            - email
            - profile
    facebook:
        client-id: "YOUR_FACEBOOK_CLIENT_ID"
        client-secret: "YOUR_FACEBOOK_CLIENT_SECRET"
        scope:
            - email
            - public_profile
    github:
        client-id: "YOUR_GITHUB_CLIENT_ID"
        client-secret: "YOUR_GITHUB_CLIENT_SECRET"
        scope:
            - user:email
            - read:user